nomes=["Alessandra","Anthony","Breno","Julio","Riki","Maria Paraná", "Matheus", "Victor"]
print(nomes)
print(nomes[2])
print(nomes[0:4])
nomes.sort()
print(nomes)
nomes.append("João")
print(nomes)
nomes.insert(4,"Daniel")
num = len(nomes)
print (num)
print(nomes)
del(nomes[4])
num = len(nomes)
print (num)
print(nomes)
del(nomes[5:6])
print(nomes)
num = len(nomes)
print (num)
del(nomes)
nomes=["Matheus"]
print(nomes)